import { StockItem } from '@/models/shared/Material'

export const materialList: StockItem[] = [
  {
    id: 12_662_740,
    total_on_hand_stock: 211,
    total_allocated_qty: 0,
    total_qty: 211,
    min: 0,
    max: 0,
    created_by: 47_750,
    updated_by: 47_750,
    created_at: '2024-07-18T07:47:01.000Z',
    updated_at: '2024-07-18T08:10:08.000Z',
    material_id: 556,
    entity_id: 122,
    material: {
      id: 556,
      name: 'Abu-abu 3',
      description: 'Abu-abu',
      code: '83013134',
      hierarchy_code: '83013134',
      consumption_unit_per_distribution_unit: 1,
      is_temperature_sensitive: 0,
      min_retail_price: 0,
      max_retail_price: 0,
      max_temperature: 0,
      min_temperature: 0,
      is_managed_in_batch: 1,
      status: 1,
      material_level_id: 3,
      material_type_id: 1,
      unit_of_consumption_id: 2,
      unit_of_distribution_id: 6,
      material_level: {
        id: 3,
        name: 'variant',
      },
      material_type: {
        id: 1,
        name: 'medicine',
      },
      unit_of_consumption: {
        id: 2,
        name: 'dosis',
      },
      unit_of_distribution: {
        id: 6,
        name: 'box',
      },
    },
    entity: {
      id: 122,
      name: 'RSIA Dhia',
      address: '',
      code: '10101',
      lat: null,
      lng: null,
      postal_code: null,
      status: 1,
      is_vendor: 1,
      is_puskesmas: 1,
      country: 'ID',
      province_id: '36',
      regency_id: '3674',
      sub_district_id: null,
      village_id: null,
      entity_tag_id: null,
      province: {
        id: '36',
        name: 'PROV. BANTEN',
      },
      regency: {
        id: '3674',
        name: 'KOTA TANGERANG SELATAN',
      },
      sub_district: {
        id: '3674',
        name: 'KOTA TANGERANG SELATAN',
      },
      entity_tag: {
        id: 7,
        title: 'Dinas Kesehatan KabKota',
      },
      entity_type: {
        id: 2,
        name: 'KOTA',
      },
    },
    stocks: [
      {
        id: 2438,
        activity: {
          id: 1,
          name: 'Rutin',
        },
        source_material: {
          id: 14,
          name: 'HIBAH',
          created_at: '2023-01-31T21:17:49.000Z',
          updated_at: '2023-01-31T21:17:49.000Z',
          deleted_at: null,
        },
        batch: {
          code: 'R9R93R',
          production_date: '2024-07-18T00:00:00.000Z',
          expired_date: '2024-07-31T14:59:59.000Z',
          manufacture_id: 6,
          manufacture: {
            name: 'Oneject',
            address: 'Jakarta, Jakarta, ID',
          },
        },
        on_hand_stock: 211,
        allocated_qty: 0,
        qty: 211,
        updated_at: '2024-07-18T08:10:08.000Z',
      },
    ],
  },
]
